# Advanced basic Python syntax

1. Variable types
    * Dictionaries
    * Variable gotcha: copy reference vs copy variable
    * Sets
    * Tuples
    * Indexing
1. List and dict comprehension
1. Functions
1. Everything is an object
1. Python and package version

# Variable types

## Dictionaries

Variable type that holds key-value pairs

### Definition

In [1]:
empty_dict = {}
empty_dict = dict()

In [2]:
d = {"name": "John", "last_name": "Smith"}
print(d)

{'name': 'John', 'last_name': 'Smith'}


### Reading entry

In [3]:
n = d["name"]
print(f"Person's name: {n}")

Person's name: John


### Adding entry

In [4]:
d = {"name": "John", "last_name": "Smith"}
print(d)

{'name': 'John', 'last_name': 'Smith'}


In [5]:
d["nice"] = True
print(d)

{'name': 'John', 'last_name': 'Smith', 'nice': True}


### Variable gotcha: copy reference vs copy variable

In [6]:
l1 = ["a", "b"]
l2 = l1  # only copies the reference to the list, not the list
l2.append("c")
print(l1)

['a', 'b', 'c']


In [7]:
print(l2)

['a', 'b', 'c']


In [8]:
l1 = ["a", "b"]
l2 = l1.copy()  # creates a copy of the list
l2.append("c")
print(l1)

['a', 'b']


In [9]:
print(l2)

['a', 'b', 'c']


### The same is true for `dicts`

In [10]:
d1 = {"a": 1}
d2 = d1
d2["i"] = 22
print(d1)

{'a': 1, 'i': 22}


In [11]:
print(d2)

{'a': 1, 'i': 22}


### ... But not for numbers or strings

In [12]:
i1 = 2
i2 = i1
i2 = 5
print(i1)

2


In [13]:
print(i2)

5


In [14]:
s1 = "a"
s2 = s1
s2 = "b"
print(s1)

a


In [15]:
print(s2)

b


## Sets: Unordered collections of unique elements

In [16]:
s = set(["a", "b"])
s

{'a', 'b'}

Sets offer a way to de-duplicate lists

In [17]:
l = ["a", "b", "a"]
s = set(l)
print(s)

{'a', 'b'}


In [18]:
# can also be done in numpy
import numpy as np

print(np.unique(l))

['a' 'b']


Handy math operations on sets

In [19]:
all_subjects = ["s1", "s2", "s3", "s4"]
available_subjects = ["s1", "s4"]

missing_subjects = set(all_subjects) - set(available_subjects)
print(missing_subjects)

{'s2', 's3'}


In [20]:
pool_1 = ["s1", "s2", "s3", "s4"]
pool_2 = ["s1", "s4", "s5", "s6"]

in_both = set(pool_1) & set(pool_2)
print(in_both)

{'s4', 's1'}


## Tuples: ordered and unchangeable
Once a tuple is defined, it cannot be changed (immutable)

In [21]:
t = ("a", "b")


### Built-In Data Structures

| Type Name | Example                   |Description                            |
|-----------|---------------------------|---------------------------------------|
| ``list``  | ``[1, 2, 3]``             | Ordered collection                    |
| ``dict``  | ``{'a':1, 'b':2, 'c':3}`` | Key-value mapping                     |
| ``tuple`` | ``(1, 2, 3)``             | Immutable ordered collection          |
| ``set``   | ``{1, 2, 3}``             | Unordered collection of unique values |

https://github.com/jakevdp/WhirlwindTourOfPython/



## Indexing
**In Python: is 0-based**

In [22]:
l = [10, 20, 30, 40]
print(l[0])  # returns first element!

10


In [23]:
l = [10, 20, 30, 40]
print(l[-1])  # returns last element!

40


In [24]:
l = [10, 20, 30, 40]
print(l[:2])  # end exclusive

[10, 20]


In [25]:
l = [10, 20, 30, 40]
print(l[2:])  # beginning inclusive

[30, 40]


In [26]:
l = [10, 20, 30, 40]
print(l[1:3])

[20, 30]


# List and dict comprehension

## List comprehension

In [27]:
fruits = ["aPPleS", "oRanges", "BananaS"]
fruits_clean = []
for fruit in fruits:
    fruits_clean.append(fruit.lower())
print(fruits_clean)

['apples', 'oranges', 'bananas']


Can be written as

In [28]:
fruits = ["aPPleS", "oRanges", "BananaS"]
fruits_clean = [fruit.lower() for fruit in fruits]
print(fruits_clean)

['apples', 'oranges', 'bananas']


## Dict comprehension

In [29]:
stock = {'apples': 3, 'oranges': 9, 'bananas': 0}
for fruit in stock:
    stock[fruit] = stock[fruit] + 1
print(stock)

{'apples': 4, 'oranges': 10, 'bananas': 1}


In [30]:
stock = {'apples': 3, 'oranges': 9, 'bananas': 0}
stock = {fruit: i + 1 for fruit, i in stock.items()}
print(stock)

{'apples': 4, 'oranges': 10, 'bananas': 1}


## Functions

* A block of code that only runs when explicitly called
* Can accept arguments (or parameters) that alter its behavior
* Can accept any number/type of inputs, but always return a single object
    * Note: functions can return tuples (may *look like* multiple objects)
    
Adapted from [Tal Yarkoni](https://github.com/neurohackademy/introduction-to-python/blob/master/introduction-to-python.ipynb)

In [31]:
# We'll need the random module for this
import random

def add_noise(x, mu, sd):
    ''' Adds gaussian noise to the input.
    
    Parameters:
        x (number): The number to add noise to
        mu (float): The mean of the gaussian noise distribution
        sd (float): The standard deviation of the noise distribution
    
    Returns: A float.
    '''
    noise = random.normalvariate(mu, sd)
    return (x + noise)

In [32]:
# Let's try calling it...
add_noise(5, 0, 2)

5.20834988660126

### Positional vs. keyword arguments
* Positional arguments are defined by position and *must* be passed
    * Arguments in the function signature are filled in order
* Keyword arguments have a default value
    * Arguments can be passed in arbitrary order (after any positional arguments)

In [33]:
def add_noise_with_defaults(x, mu=0, sd=1):
    ''' Adds gaussian noise to the input.
    
    Parameters:
        x (number): The number to add noise to
        mu (float): The mean of the gaussian noise distribution
        sd (float): The standard deviation of the noise distribution
    
    Returns: A float.
    '''
    noise = random.normalvariate(mu, sd)
    return x + noise

In [34]:
add_noise_with_defaults(5, mu=0, sd=1)

5.297644808186795

In [35]:
add_noise_with_defaults(5)

4.666092972477043

In [36]:
add_noise_with_defaults(5, mu=3)

7.1932736631316185

In [37]:
add_noise_with_defaults(5, sd=3)

1.7869981464308786

## Functions in modules
Let's create an array with numpy

In [38]:
import numpy as np

data = np.array([[1, 2], [10, 20]])
print(data)

[[ 1  2]
 [10 20]]


We can calculate the mean with the `np.mean` function:

In [39]:
m = np.mean(data)
print(m)

8.25


To get a list of arguments, check the `np.mean` function's help:

In [40]:
help(np.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs,

# Everything is an object

Python is an object-oriented programming language, and in Python everything is an object.
* variables
* functions
* modules
* ...

The operations you can perform with an object depend on the object's definition. E.g., calling `help` works on all of them.

Objects can have 
1. **attributes** : something that describes the object, and 
1. **methods**: a fuction of the object

For example, before we saw that lists have an ``append`` method, which adds an item to the list, and is accessed via the dot ("``.``") syntax:

In [41]:
L = [1, 2, 3]
L.append(100)
print(L)

[1, 2, 3, 100]


In [42]:
import numpy as np

a = np.array([[1, 2, 3], [11, 22, 44]])
a

array([[ 1,  2,  3],
       [11, 22, 44]])

### Attributes 

In [43]:
a.shape

(2, 3)

### Methods

In [44]:
a.flatten()

array([ 1,  2,  3, 11, 22, 44])

Note the difference re. **brackets!**

# Python and package version

In [45]:
import sys
print(sys.version)

3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ]


In [46]:
import numpy as np
print(np.__version__)

1.18.5


or run
```bash 
conda list
```

in the terminal to get a list of all packages